export const logos: { [_: string]: string } = {
    ansible: require('../image/skill/ansible.png').default,
    drupal: require('../image/skill/drupal.png').default,
    elasticsearch: require('../image/skill/elasticsearch.png').default,
    git: require('../image/skill/git.png').default,
    javascript: require('../image/skill/javascript.png').default,
    laravel: require('../image/skill/laravel.png').default,
    nginx: require('../image/skill/nginx.png').default,
    php: require('../image/skill/php.png').default,
    python: require('../image/skill/python.png').default,
    react: require('../image/skill/react.png').default,
    sass: require('../image/skill/sass.png').default,
    symfony: require('../image/skill/symfony.png').default,
    wordpress: require('../image/skill/wordpress.png').default,
}
